{% set name = "OpenFisca-Core" %}
{% set version = "35.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9509cf7733fd3a1ab6225a3b6f799e595ce928a9bdcfc4d863a3e9bd0f920380


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - openfisca = openfisca_core.scripts.openfisca_command:main
    - openfisca-run-test = openfisca_core.scripts.openfisca_command:main

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.6,<4.0
    - dpath >=1.5.0,<3.0.0
    - nptyping ==1.4.4
    - numexpr >=2.7.0,<=3.0
    - numpy >=1.11,<1.21
    - psutil >=5.4.7,<6.0.0
    - pytest >=4.4.1,<6.0.0
    - PyYAML >=3.10
    - sortedcontainers ==2.2.2
    - typing-extensions ==3.10.0.2

test:
  imports:
    - openfisca_core
    - openfisca_core.commons
  requires:
    - pytest >=4.4.1,<6.0.0
    - pip
  commands:
    - pip check
    - openfisca --help
    - openfisca-run-test --help

outputs:
  - name: openfisca-core

  - name: openfisca-core-api
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - python >=3.6,<4.0
        - flask ==1.1.2
        - flask-cors ==3.0.10
        - gunicorn >=20.0.0,<21.0.0
        - werkzeug >=1.0.0,<2.0.0
        - {{ pin_subpackage('openfisca-core', exact=True) }}

  - name: openfisca-core-dev
    build:
      noarch: python
    requirements:
      host:
        - python
      run:
        - autopep8 >=1.4.0,<1.6.0
        - coverage ==6.0.2
        - darglint ==1.8.0
        - flake8 >=3.9.0,<4.0.0
        - flake8-bugbear >=19.3.0,<20.0.0
        - flake8-docstrings ==1.6.0
        - flake8-print >=3.1.0,<4.0.0
        - flake8-rst-docstrings ==0.2.3
        - mypy ==0.910
        - openfisca-country-template >=3.10.0,<4.0.0
        - openfisca-extension-template >=1.2.0rc0,<2.0.0
        - pylint ==2.10.2
        - {{ pin_subpackage('openfisca-core-api', exact=True) }}

about:
  home: https://openfisca.org
  license_family: AGPL
  license: AGPL-3.0-only
  license_file: LICENSE
  summary: A versatile microsimulation free software
  doc_url: https://openfisca.org
  dev_url: https://github.com/openfisca/openfisca-core/
  description: This package contains the core features of OpenFisca, which are meant to be used by country packages such as OpenFisca-France.

extra:
  recipe-maintainers:
    # GitHub IDs for maintainers of the recipe.
    # Always check with the people listed below if they are OK becoming maintainers of the recipe. (There will be spam!)
    - benoit-cty
    - benjello
    - sandcha
    - eraviart
    - MattiSG
